### ISSUE TITLE
Design das lojas

### ISSUE THREAD

**Issue by thaisclxt** [thaisclxt/proj-sist-2021-2#1]
Dei uma olhada na branch `feature/lojas` e ao passar o mouse pelo container de uma loja, notei que este está menor que o ideal. O cupom de desconto está colado com o container, é melhor deixar o container maior.

- No Ifood
![image](https://user-images.githubusercontent.com/62521620/136092907-9bf016b1-1b05-4e20-bf7d-c09b780dd1c2.png)

- No projeto
![image](https://user-images.githubusercontent.com/62521620/136093271-88f8f38f-c790-48cf-bc86-3b2c98355644.png)

**Comment by Ericboo** [comment]
O card foi aumentado. Ainda não é tão responsivo verticalmente quanto o card do ifood, estamos trabalhando nisso.
![Captura de tela 2021-10-05 194541](https://user-images.githubusercontent.com/59875728/136112959-e9dbe708-e934-4249-a1fb-77fba7fe13e4.png)
